In [ ]:
import kagglehub

# Get the data locally:
path = kagglehub.dataset_download("akhiljethwa/blood-cancer-image-dataset", output_dir='./.cache')
print("Path to dataset files:", path)

100%|██████████| 102M/102M [00:37<00:00, 2.84MB/s] 

Extracting files...


Path to dataset files: ./.cache


In [ ]:
import numpy as np
from pathlib import Path
from skimage.io import imread
from multiprocessing import Pool, cpu_count

# Find all the files:
path = Path(path)
try:
    files_list = [file for file in path.rglob('*.tiff')]
    print(len(files_list), 'files found.')
except Exception as e:
    print('Error finding files:', e)

# Extract image data into a NumPy array:
n_processes = min(4, cpu_count() // 2)
with Pool(processes=n_processes) as pool:
    img_data_arr = pool.map(imread, files_list)

# Create an master NumPy array (n_images x h x w x n_channels)
img_data_arr = np.array(img_data_arr)
print('Image data array shape:', img_data_arr.shape)
np.save('./.cache/Blood_Cancer.npy', img_data_arr)


10000 files found.
Image data array shape: (10000, 64, 64, 4)


The NumPy array of all the images shows that there are four (4) "layers" of data for each image. I'm guessing this is a CMYK structure, but don't really know how to confirm.

In [ ]:
# Example of the layers of the image:
for layer in range(4):
    print(f'\nLayer {layer}:\n', img_data_arr[0, :, :, layer])


Layer 0:
 [[241 239 239 ... 227 227 227]
 [240 239 239 ... 227 227 226]
 [241 240 241 ... 228 227 226]
 ...
 [220 219 220 ... 222 221 222]
 [222 222 222 ... 221 222 222]
 [222 222 223 ... 222 223 223]]

Layer 1:
 [[239 238 240 ... 204 201 201]
 [239 238 239 ... 205 203 202]
 [239 238 238 ... 202 204 203]
 ...
 [197 194 191 ... 192 194 194]
 [200 199 198 ... 192 195 195]
 [201 200 202 ... 199 198 198]]

Layer 2:
 [[234 235 234 ... 209 210 209]
 [233 234 236 ... 209 211 209]
 [231 233 234 ... 207 211 210]
 ...
 [211 207 206 ... 204 205 208]
 [212 210 209 ... 205 206 210]
 [212 211 209 ... 211 210 211]]

Layer 3:
 [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
